import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'
import Dummy from '../components/dummy'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        .myspan{
          color: red
        }
          
        `}
      </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="blogs, hunting coder blogs, nextjs, coding" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/src.js" strategy='lazyOnload'></Script> */}
          <Dummy/>
      <nav className={styles.nav}>
        <ul>
         <Link href={'/'}> <li>Home</li></Link>
         <Link href={'/about'}><li>About</li></Link>
           <Link href={'/contact'}><li>Contact</li></Link>
          <Link href={'/blog'}> <li>Blog</li></Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={[styles.title]}>
          <span className='myspan dummy'>
          Hunting Coder
          </span>
        </h1>

        <p className={styles.description}>
          A blogs for hunting coders for hunting coder
        </p>

        <div className="blogs">
          
          <div className="blogitem">
            <h3>Learn JS in 2023?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
          </div>
        </div>
      </main>

   
    </div>
  )
}
