import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script'


export default function Home() {
  return (
    <div className={styles.container}>
      {/* <style jsx>
        {`
          h2{
          // font-size: 35px
          }
        `}
      </style> */}
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="blogs, hunting coder blogs, nextjs, coding" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img className={styles.myimg} src="/blog1.jpg" width={237} height={158} />
        <h1 className={[styles.title]}>
          <span className='myspan dummy'>
            &lt;Hunting Coder/&gt;
          </span>
        </h1>


        <p className={styles.description}>
          A blogs for hunting coders for hunting coder
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogitem">
            <h3 className={styles.topic}>Learn Flask in 2023?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            <button className={styles.btn}>Read More...</button>
          </div>
          <div className="blogitem">
            <h3 className={styles.topic}>Learn JS in 2023?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            <button className={styles.btn}>Read More...</button>
          </div>
          <div className="blogitem">
            <h3 className={styles.topic}>Learn Next js in 2023?</h3>
            <p >Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            <button className={styles.btn}>Read More...</button>
          </div>
        </div>
      </main>


    </div>
  )
}
